// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNeKJzqtgoazRCZdUHgupmxiiGNESs8Q0',
    appId: '1:514521584197:web:acb22b04663c106a43092c',
    messagingSenderId: '514521584197',
    projectId: 'women-safety-app-fbed8',
    authDomain: 'women-safety-app-fbed8.firebaseapp.com',
    storageBucket: 'women-safety-app-fbed8.firebasestorage.app',
    measurementId: 'G-FG10NPDNL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3lN1CULI_ilwc-yOcS_9w6_T_bNRUQc',
    appId: '1:514521584197:android:202ad7081d60ae7243092c',
    messagingSenderId: '514521584197',
    projectId: 'women-safety-app-fbed8',
    storageBucket: 'women-safety-app-fbed8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjz1LQzdoeRzELk5hZanAEym-2QmLXpi4',
    appId: '1:514521584197:ios:b5269462e992ea9643092c',
    messagingSenderId: '514521584197',
    projectId: 'women-safety-app-fbed8',
    storageBucket: 'women-safety-app-fbed8.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjz1LQzdoeRzELk5hZanAEym-2QmLXpi4',
    appId: '1:514521584197:ios:b5269462e992ea9643092c',
    messagingSenderId: '514521584197',
    projectId: 'women-safety-app-fbed8',
    storageBucket: 'women-safety-app-fbed8.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNeKJzqtgoazRCZdUHgupmxiiGNESs8Q0',
    appId: '1:514521584197:web:d1dec36437bd8cbc43092c',
    messagingSenderId: '514521584197',
    projectId: 'women-safety-app-fbed8',
    authDomain: 'women-safety-app-fbed8.firebaseapp.com',
    storageBucket: 'women-safety-app-fbed8.firebasestorage.app',
    measurementId: 'G-RTD60WED00',
  );

}